name: Continuous Integration 

on: [push, pull_request]

jobs:
  ci:
    strategy:
      matrix:
        platform: [ubuntu-latest]
        node: [ '16', '14', '12' ]
    name: CI - Node ${{ matrix.node }} (${{ matrix.platform }})
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: npm install --no-optional --no-save --no-update-notifier
      - name: Run tests
        run: npm run test
        
  ci-old-node:
    strategy:
      matrix:
        platform: [ubuntu-latest]
        node: [ '10' ]
    name: CI - Node ${{ matrix.node }} (${{ matrix.platform }})
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: npm install --no-optional --no-save --no-update-notifier
      - name: Run tests
        run: npm run test:unit
        
